---
output: 
  html_document:
    fig_caption: yes
    css: stylesheets/custom_styles.css
    anchor_sections: FALSE
    includes: 
      in_header: "header_manual.html" 
      after_body: "footer.html"
params:
  park: ACAD
  from: 2006
  to: 2018
  current: 2019
  cat: physical
  nutrient: TRUE
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.pos = "h")
```

```{r libs, include = FALSE, results = 'hide'}
##------------------------------------------------------------------------------
## Load data and libraries
##------------------------------------------------------------------------------
library(NCRNWater)
library(tidyverse)
library(plotly)
library(purrr)
library(htmltools)
library(leaflet)
library(viridis)
library(kableExtra)
```
```{r import}
path = "C:/Users/Diana/Documents/NETN/Water/data"
#path = "D:/NETN/R_Dev/Water/NCRNWaterViz/Data/NETN"
netnwd <- importNCRNWater(Dir = path, 
                          Data = "Water Data.csv", 
                          MetaData = "VizMetaData.csv")

```

```{r globvars, message = F}
##------------------------------------------------------------------------------
## Global variables
##------------------------------------------------------------------------------
# Variables for cat asis code, which can't take params
parkcode = params$park
current = params$current
from = params$from
to = params$to
category = params$cat

# Long park name
long_name = getParkInfo(netnwd, park = params$park, info = "ParkLongName")

# List of sites
site_list_all <- getSiteInfo(netnwd, park = params$park, info = "SiteCode")
sites_curr <- getWData(netnwd, park = params$park, years = params$current) %>% 
                select(Site) %>% unique()

# Set up site_list so only includes sites sampled in current year
site_list <- site_list_all[site_list_all %in% sites_curr$Site] 

# Get list of site names
site_names <- getSiteInfo(netnwd, park = params$park, sitecode = site_list, info = "SiteName")

# Create site key for sitecode and type
site_key <- data.frame(Site = getSiteInfo(netnwd, parkcode = parkcode, info = "SiteCode"),
                         SiteType =  getSiteInfo(netnwd, parkcode = parkcode, info = "type"))

# Create dataframe of sites measured during target year and site type
site_df <- as.data.frame(site_list)
colnames(site_df) <- "sitecode"
site_df <- left_join(site_df, site_key, by = c("sitecode"="Site"))

# Filter dataframe to create lists of lake and stream sites 
# (There must be a less repetitive way to do this)
site_list_lake <- site_df %>% filter(SiteType == "Lake")
site_list_lake <- site_list_lake$sitecode

site_list_stream <- site_df %>% filter(SiteType == "Stream")
site_list_stream <- site_list_stream$sitecode

# Turn on comp tab if park has more than one site
show_comp <- ifelse(length(site_list) > 1, TRUE, FALSE)

```

```{r waterboxplot}
# Variables to turn on for function troubleshooting
# char_list <- getCharInfo(netnwd, parkcode = parkcode, category = "nutrients",
#                          info = "CharName") %>% unique()
# sitecode <- site_list[2]
# charname <- char_list[2]

waterboxplot <- function(sitecode, charname) {

  # params for package function
  parkcode <- params$park
  category <- "nutrients"
  object <- netnwd
  assessment <- TRUE # function param for assessment line
  
  # Compile water data for target years (from - current) and add columns for month, 
  # historical and current year data, upper and lower assessment, and outlier color
  wdat <- getWData(object, parkcode = parkcode, sitecode = sitecode, 
                 charname = charname, category = category,
                 years = from:current) %>% 
  mutate(month = lubridate::month(Date, label = TRUE, abbr = TRUE), 
         month_num = as.numeric(month), 
         year = lubridate::year(Date),
         
         # round value to one decimal point
         # ValueCen = round(ValueCen, digits = 1),
         
         # Create separate columns for current and historical values
         # ValueCen_curr = ifelse(year == current, ValueCen, NA),
         # ValueCen_hist = ifelse(year != current, ValueCen, NA),
         
         # Import lower and upper assessment values
         LowerPoint = ifelse(assessment == TRUE, 
                             getCharInfo(object, parkcode = parkcode, sitecode = sitecode, 
                                         charname = charname, category = category, 
                                         info = "LowerPoint"), NA),
         UpperPoint = ifelse(assessment == TRUE, 
                             getCharInfo(object, parkcode = parkcode, sitecode = sitecode, 
                                         charname = charname, category = category, 
                                         info = "UpperPoint"), NA),
         
         # Assess quality of current measurement to later set marker color
         pcolor = 
           ifelse(!is.na(UpperPoint) & year == current & ValueCen > UpperPoint, "Poor WQ value",
           ifelse(!is.na(LowerPoint) & year == current & ValueCen < LowerPoint, "Poor WQ value", "Current value"))
         ) %>%
  
  arrange(Date) %>% 
    
  # Add site type column  
  left_join(., site_key, by = "Site")

  # Select target months using site type
  # Note: this may have problems later if target months are different
  if (all(wdat$SiteType == "Lake")) {
    wdat <- filter(wdat, month == "Jun" | month == "Aug")} else {
      wdat <- filter(wdat, month == "May" | month == "Aug")
    }
  
  # Separate water data by current/historical so boxplots include only hist data
  wdat_hist <- wdat %>% filter(year <= to)
  wdat_curr <- wdat %>% filter(year == current)
  
  # Parameter name for tooltips
  param_name <- getCharInfo(object, parkcode = parkcode, sitecode = sitecode,
                            charname = charname, info = "CategoryDisplay") %>% unique()
  
  # Unit for tooltips
  unit <- getCharInfo(object, parkcode = parkcode, sitecode = sitecode, 
                      charname = charname, info = "Units") %>% unique()
  
  # Y axis name (parameter + units in parentheses)
  yname <- ifelse(charname != "pH", 
                  paste0(getCharInfo(object, parkcode = parkcode, sitecode = sitecode,
                                     charname = charname, info = "CategoryDisplay") %>% unique(), " (", 
                         getCharInfo(object, parkcode = parkcode, sitecode = sitecode,
                                     charname = charname, info = "Units") %>% unique(),                           
                         ")"),
                  paste0(getCharInfo(object, parkcode = parkcode, sitecode = sitecode,
                                     charname = charname, info = "CategoryDisplay") %>% unique()))
  
  # Set y axis style for plotly
  yaxis = list(
    title = yname,
    showline = TRUE,
    showgrid = FALSE,
    autotick = TRUE,
    ticks = "outside"
  )
  
  # Set x axis style for plotly
  xaxis = list(
    title = FALSE, 
    showline = TRUE,
    showgrid = FALSE,
    autotick = FALSE,
    ticks = "outside",
    #ticktext = list("Jun", "Aug"),
    ticktext = sort(unique(wdat$month)),
    #tickvals = list(6, 8),
    tickvals = sort(unique(wdat$month_num)),
    tickmode = "array"
  )
  
  # Create marker tooltip for hovertemplate
  hover = paste0('%{x} ', current, '<br>', # Month Year
                 param_name, ': %{y} ', unit, # Parameter value units
                 '<extra></extra>') # this removes the secondary text box in the tooltip
  
  p <- plot_ly(wdat_hist, x = ~month_num, y = ~ValueCen) %>%
    
    # Boxplots historic range
    add_boxplot(boxpoints = "outliers", name = "Historic range", 
                marker = list(symbol='asterisk-open', size = 7, color = "#1378b5"),
                fillcolor = list(color = "#1378b5", alpha = 0.85),
                line = list(color = "#1378b5")) %>% #, showlegend = FALSE) %>%  
    
    # Current year measurements
    # Use pcolor to set color and name of markers
    add_markers(data = wdat_curr[wdat_curr$pcolor=="Current value",], 
                name = "Current value",
                marker = list(color = "black", size = 7),
                hovertemplate = hover) %>% 
                
    add_markers(data = wdat_curr[wdat_curr$pcolor=="Poor WQ value",], 
                name = "Poor WQ value",
                marker = list(color = "orange", size = 7),
                hovertemplate = hover) %>% 
    
    # Set x axis and y axis styles
    layout(xaxis = xaxis, yaxis = yaxis, 
           # make legend horizontal
           legend = list(orientation = "h"))
  
  # Set value for WQ threshold line 
  UpperPoint <- unique(wdat_curr$UpperPoint)
  
  # Find min and max months
  wq_x <- min(unique(wdat$month_num))
  wq_xend <- max(unique(wdat$month_num))

  # Calculate length of WQ line based on plotted months
  wq_xend <- ifelse(wq_x == 6, wq_xend+1,
                 ifelse(wq_x == 5, wq_xend+1.5,
                        NA))
  wq_x <- ifelse(wq_x == 6, wq_x-1,
                 ifelse(wq_x == 5, wq_x-1.5,
                        NA))
  
  # If there is an upper threshold value, add WQ line to plot
  ifelse(!is.na(UpperPoint), 
         p <- p %>% add_segments(y = UpperPoint, yend = UpperPoint,
                  x = wq_x, xend = wq_xend, # length of line
                  text = paste("Upper", param_name, "threshold:", UpperPoint, unit),
                  hoverinfo = "text", # set tooltip text
                  line = list(color = "black", dash = "dash"),
                  name = "WQ threshold"),
         NA)

  return(p)

  }
```

```{r, site_comp_setup, echo = F, warning = F, message = F, eval = show_comp}
##------------------------------------------------------------------------------
## LAKES - Physical site comp setup
##------------------------------------------------------------------------------
# List of physical lake parameters (excludes discharge)
char_list_p <- getCharInfo(netnwd, parkcode = params$park, category = params$cat, 
                         info = "CharName") %>%
                         unique() %>% #remove duplicates
                         .[!.=="Discharge_cfs"] #remove discharge

# Turn off all legends except last in list to remove legend duplicates from subplot
legend_list_p <- c(rep("none", length(char_list_p)-1), "bottom")

# Create list of plots comparing physical parameters across all lakes in park
comp_plots_p <- purrr::map2(char_list_p, legend_list_p,
                         ~watersite_comps(netnwd, year = params$current, 
                                     parkcode = params$park, 
                                     sitecode = site_list_lake,
                                     charname = .x,
                                     legend = .y)) %>%
              set_names(char_list_p) #name plots to refer to them by char name

heights_p <- c(0.5,0.5)

# Use plot list to create matrix of plots (plotly subplot)
comp_plots_p_final <- subplot(comp_plots_p[1:length(comp_plots_p)],
                         titleY = TRUE, titleX = FALSE, margin = 0.05,
                         #create 3 rows if more than 4 plots, otherwise 2 rows
                         nrows = ifelse(length(comp_plots_p)> 4, 3, 2),
                         #set height of each row (default makes middle row shorter)
                         heights = heights_p) %>% 
  # turn off subplot legend
  style(showlegend = FALSE) %>% 
  # manually set width and height of subplot
  layout(autosize = FALSE, width = 900, height = 650)

num_sites <- c(1:length(site_list_lake))

# Turn on legend elements 
for (i in 1:length(num_sites)){
  comp_plots_p_final$x$data[[i]]$showlegend <- TRUE #site (line/markers)
  #comp_plots_p_final$x$data[[length(comp_plots_p_final$x$data)]]$showlegend <- TRUE #threshold line
  #comp_plots_p_final$x$data[[length(comp_plots_p_final$x$data)]]$name <- "WQ Threshold" #set name
}

# Move legend down slightly and make it horizontal
comp_plots_p_final <- comp_plots_p_final %>% layout(legend = list(x = 0, y = -0.05, orientation = "h"))

##------------------------------------------------------------------------------
## LAKES - Nutrients site comp setup
##------------------------------------------------------------------------------
# List of nutrient parameters to include in site comparison
char_list_n <- c("TN_mgL", "TP_ugL")

# Turn off all legends except last in list to remove legend duplicates from subplot
legend_list_n <- c(rep("none", length(char_list_n)-1), "bottom")

# Create list of plots comparing physical parameters across all sites in park
comp_plots_n <- purrr::map2(char_list_n, legend_list_n,
                         ~watersite_comps(netnwd, 
                                          year = params$current, 
                                          parkcode = params$park, 
                                          sitecode = site_list_lake,
                                          charname = .x,
                                          legend = .y)) %>%
              set_names(char_list_n) #name plots to refer to them by char name

# Use plot list to create matrix of plots (plotly subplot)
comp_plots_n_final <- subplot(comp_plots_n[1:length(comp_plots_n)],
                         titleY = TRUE, titleX = FALSE, margin = 0.05, nrows = 1) %>% 
  # turn off subplot legend, manually set height and width of subplot
  style(showlegend = FALSE) %>% layout(autosize = FALSE, width = 900, height = 300)

num_sites <- c(1:length(site_list_lake))

# Turn on legend elements 
for (i in 1:length(num_sites)){
  comp_plots_n_final$x$data[[i]]$showlegend <- TRUE #site (line/markers)
  #comp_plots_n_final$x$data[[length(comp_plots_n_final$x$data)]]$showlegend <- TRUE #threshold line
  #comp_plots_n_final$x$data[[length(comp_plots_n_final$x$data)]]$name <- "WQ Threshold" #set name
}

# Move legend down slightly and make it horizontal
comp_plots_n_final <- comp_plots_n_final %>% layout(legend = list(x = 0, y = -0.12, orientation = "h"))

```

# `r long_name` {.tabset .tabset-fade .tabset-pills}

```{r, p_site_comp, results = 'asis', include = show_comp}
##------------------------------------------------------------------------------
## Physical site comp plots                            
##------------------------------------------------------------------------------
# Create lake tab
cat("## ", "Lakes","{.tabset}", "\n")

# Lake comparison tab
cat("### ", "All Lakes","{.tabset}", "\n")

# Create a physical parameter subtab if also reporting nutrients
if(params$nutrient==TRUE) {cat("#### ", "Field Measurements", "\n")}

# Title of tab
cat("<h2>Monthly Water Quality Measurements", paste0("(", parkcode, " ", current, ")"),"</h2>")

# Figure caption 
fig_cap <- htmltools::withTags(body(
                          'The plots below compare monthly
                          measurements across all', long_name, 'sites during the',
                          current, 'field season. Only water quality parameters
                          that are measured at multiple sites are included. WQ thresholds
                          are derived from state surface water quality standards. Parameter 
                          abbreviations and additional information are defined in
                          "About the Data".'))

cat(as.character(fig_cap))
```
```{r, p_site_comp_plots, results = 'show', out.height = "90%", eval = show_comp}
comp_plots_p_final

# NOTE: The space directly below between p_site_comp and n_site_comp is necessary 
# for tabset to work in a combined report (physical and nutrients) 
# Adding cat("\n") does not work
```

```{r, n_site_comp, results = 'asis', include = show_comp}
##------------------------------------------------------------------------------
## Nutrient site comp plots                            
##------------------------------------------------------------------------------
# Create nutrient subtab if reporting nutrients
if(params$nutrient==TRUE) {cat("#### ", "Lab Chemistry", "\n")}

# Subtab title
if(params$nutrient==TRUE) {cat("<h2>Monthly Water Quality Measurements", paste0("(", parkcode, " ", current, ")"),"</h2>")}

# Figure caption
fig_cap <- htmltools::withTags(body(
                          'The plots below compare monthly
                          measurements across all', long_name, 'sites during the',
                          current, 'field season. Only water quality parameters
                          that are measured at multiple sites are included. WQ thresholds
                          are derived from state surface water quality standards. Parameter 
                          abbreviations and additional information are defined in 
                          "About the Data".'))

if(params$nutrient==TRUE) {cat(as.character(fig_cap))}
```
```{r, n_site_comp_plots, results = 'show', out.height = "90%", eval = show_comp}
if(params$nutrient==TRUE) {comp_plots_n_final}
```