---
output: 
  html_document:
    fig_caption: yes
    css: stylesheets/custom_styles.css
    anchor_sections: FALSE
    includes: 
      in_header: "header_manual.html" 
      after_body: "footer.html"
params:
  park: MABI
  from: 2006
  to: 2018
  current: 2019
  cat: physical
  nutrient: TRUE
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.pos = "h")
```

```{r libs, include = FALSE, results = 'hide'}
##------------------------------------------------------------------------------
## Load data and libraries
##------------------------------------------------------------------------------
library(NCRNWater)
library(tidyverse)
library(plotly)
library(purrr)
library(htmltools)
library(leaflet)
library(viridis)
library(kableExtra)
```
```{r import}
path = "C:/Users/Diana/Documents/NETN/Water/data"
#path = "D:/NETN/R_Dev/Water/NCRNWaterViz/Data/NETN"
netnwd <- importNCRNWater(Dir = path, 
                          Data = "Water Data.csv", 
                          MetaData = "VizMetaData.csv")

```

```{r globvars, message = F}
##------------------------------------------------------------------------------
## Global variables
##------------------------------------------------------------------------------
# Variables for cat asis code, which can't take params
parkcode = params$park
current = params$current
from = params$from
to = params$to
category = params$cat

# Long park name
long_name = getParkInfo(netnwd, park = params$park, info = "ParkLongName")

# List of sites
site_list_all <- getSiteInfo(netnwd, park = params$park, info = "SiteCode")
sites_curr <- getWData(netnwd, park = params$park, years = params$current) %>% 
                select(Site) %>% unique()

# Set up site_list so only includes sites sampled in current year
site_list <- site_list_all[site_list_all %in% sites_curr$Site] 

# Get list of site names
site_names <- getSiteInfo(netnwd, park = params$park, sitecode = site_list, info = "SiteName")

# Create site key for sitecode and type
site_key <- data.frame(Site = getSiteInfo(netnwd, parkcode = parkcode, info = "SiteCode"),
                         SiteType =  getSiteInfo(netnwd, parkcode = parkcode, info = "type"))

show_comp <- ifelse(length(site_list) > 1, TRUE, FALSE)

```

```{r waterboxplot}
waterboxplot <- function(sitecode, charname) {

  # params for package function
  parkcode <- params$park
  category <- "nutrients"
  object <- netnwd
  assessment <- TRUE # function param for assessment line
  
  # Compile water data for target years (from - current) and add columns for month, 
  # historical and current year data, upper and lower assessment, and outlier color
  wdat <- getWData(object, parkcode = parkcode, sitecode = sitecode, 
                 charname = charname, category = category,
                 years = from:current) %>% 
  mutate(month = lubridate::month(Date, label = TRUE, abbr = TRUE), 
         month_num = as.numeric(month), 
         year = lubridate::year(Date),
         ValueCen_curr = ifelse(year == current, ValueCen, NA),
         ValueCen_hist = ifelse(year != current, ValueCen, NA),
         LowerPoint = ifelse(assessment == TRUE, 
                             getCharInfo(object, parkcode = parkcode, sitecode = sitecode, 
                                         charname = charname, category = category, 
                                         info = "LowerPoint"), NA),
         UpperPoint = ifelse(assessment == TRUE, 
                             getCharInfo(object, parkcode = parkcode, sitecode = sitecode, 
                                         charname = charname, category = category, 
                                         info = "UpperPoint"), NA), 
         pcolor = ifelse(!is.na(UpperPoint) & ValueCen_curr > UpperPoint, "Poor WQ value",
                         ifelse(!is.na(LowerPoint) & ValueCen_curr < LowerPoint, "Poor WQ value", "Current value"))) %>%
  arrange(Date) %>% 
  left_join(., site_key, by = "Site")

  # Filter target months based on site type
  # note: this may have problems later if target months are different
  if (all(wdat$SiteType == "Lake")) {
    wdat <- filter(wdat, month == "Jun" | month == "Aug")} else {
      wdat <- filter(wdat, month == "May" | month == "Aug")
    }
  
  #wdat$pcolor <- factor(wdat$pcolor, levels = c("Current value", "Poor WQ value"))
  wdat_hist <- wdat %>% filter(year <= to)
  wdat_curr <- wdat %>% filter(year == current)
  
  param_name <- getCharInfo(object, parkcode = parkcode, sitecode = sitecode,
                            charname = charname, info = "CategoryDisplay") %>% unique()
  
  unit <- getCharInfo(object, parkcode = parkcode, sitecode = sitecode, 
                      charname = charname, info = "Units") %>% unique()
  
  yname <- ifelse(charname != "pH", 
                  paste0(getCharInfo(object, parkcode = parkcode, sitecode = sitecode,
                                     charname = charname, info = "CategoryDisplay") %>% unique(), " (", 
                         getCharInfo(object, parkcode = parkcode, sitecode = sitecode,
                                     charname = charname, info = "Units") %>% unique(),                           
                         ")"),
                  paste0(getCharInfo(object, parkcode = parkcode, sitecode = sitecode,
                                     charname = charname, info = "CategoryDisplay") %>% unique()))
  
  # set y axis style 
  yaxis = list(
    title = yname,
    showline = TRUE,
    showgrid = FALSE,
    autotick = TRUE,
    ticks = "outside"
  )
  
  # set x axis style
  xaxis = list(
    title = FALSE, 
    showline = TRUE,
    showgrid = FALSE,
    autotick = FALSE,
    ticks = "outside",
    #ticktext = list("Jun", "Aug"),
    ticktext = sort(unique(wdat$month)),
    #tickvals = list(6, 8),
    tickvals = sort(unique(wdat$month_num)),
    tickmode = "array"
  )
  
  # Create color key for current year points
  # This displays the correct labels in the legend
  color_map = c("Poor WQ value" = "orange", "Current value" = "black")
  
  p <- plot_ly(wdat_hist, x = ~month_num, y = ~ValueCen) %>%
    
    add_boxplot(boxpoints = "outliers", name = "Historic range", 
                marker = list(symbol='asterisk-open', size = 7, color = "#1378b5"),
                fillcolor = list(color = "#1378b5", alpha = 0.85),
                line = list(color = "#1378b5")) %>% #, showlegend = FALSE) %>%  
    
    # add_markers(data = wdat_curr, color = ~pcolor,
    #             #marker = list(color = wdat_curr$pcolor, size = 7), 
    #             marker = list(color = color_map[wdat_curr$pcolor], size = 7),
    #             split = wdat_curr$pcolor,
    #             text = paste0(wdat_curr$month, " ", current, "<br>",
    #                           param_name, ": ", round(wdat_curr$ValueCen_curr, 1), " ", unit), 
    #             hoverinfo = "text") %>%
    add_markers(data = wdat_curr[wdat_curr$pcolor=="Current value",], name = "Current value",
                marker = list(color = "black", size = 7)) %>% #,
                # text = paste0(wdat_curr$month, " ", wdat_curr$year, "<br>", 
                #        param_name, ": ", round(wdat_curr$ValueCen_curr, 1), " ", unit),
                # hoverinfo = 'text') %>% 
    
    add_markers(data = wdat_curr[wdat_curr$pcolor=="Poor WQ value",], name = "Poor WQ value",
                marker = list(color = "orange", size = 7)) %>% #,
                # text = paste0(wdat_curr$month, " ", wdat_curr$year, "<br>", 
                #        param_name, ": ", round(wdat_curr$ValueCen_curr, 1), " ", unit),
                # hoverinfo = 'text') %>%
    
    layout(xaxis = xaxis, yaxis = yaxis, legend = list(orientation = "h"))
  
  # set value for WQ threshold line
  UpperPoint <- unique(wdat_curr$UpperPoint)
  
  # Find min and max months
  wq_x <- min(unique(wdat$month_num))
  wq_xend <- max(unique(wdat$month_num))

  # Calculate length of WQ line based on plotted months
  wq_xend <- ifelse(wq_x == 6, wq_xend+1,
                 ifelse(wq_x == 5, wq_xend+1.5,
                        NA))
  wq_x <- ifelse(wq_x == 6, wq_x-1,
                 ifelse(wq_x == 5, wq_x-1.5,
                        NA))
  
  # if value is not NA, add WQ threshold 
  ifelse(!is.na(UpperPoint), 
         p <- p %>% add_segments(y = UpperPoint, yend = UpperPoint,
                  x = wq_x, xend = wq_xend,
                  text = paste("Upper", param_name, "threshold:", UpperPoint, unit),
                  hoverinfo = "text",
                  line = list(color = "black", dash = "dash"),
                  name = "WQ threshold"),
         NA)

  return(p)

  }
```
```{r, site_comp_setup, echo = F, warning = F, message = F, eval = show_comp}
##------------------------------------------------------------------------------
## Physical site comp setup
##------------------------------------------------------------------------------

char_list_p <- getCharInfo(netnwd, parkcode = params$park, category = params$cat, 
                         info = "CharName") %>% #.[duplicated(.)] %>% 
                         unique()

legend_list_p <- c(rep("none", length(char_list_p)-1), "bottom")

comp_plots_p <- purrr::map2(char_list_p, legend_list_p,
                         ~watersite_comps(netnwd, year = params$current, 
                                     parkcode = params$park, 
                                     sitecode = site_list,
                                     charname = .x,
                                     legend = .y)) %>%
              set_names(char_list_p) #name plots to refer to them by char name

comp_plots_p_final <- subplot(comp_plots_p[1:length(comp_plots_p)],
                         titleY = TRUE, titleX = FALSE, margin = 0.05,
                         nrows = ifelse(length(comp_plots_p)> 4, 3, 2),
                         heights = c(0.3, 0.35, 0.3)) %>% 
  style(showlegend = FALSE) %>% layout(autosize = FALSE, width = 900, height = 650)

num_sites <- c(1:length(site_names))

for (i in 1:length(num_sites)){
  comp_plots_p_final$x$data[[i]]$showlegend <- TRUE #first set of site elements 
  comp_plots_p_final$x$data[[length(comp_plots_p_final$x$data)]]$showlegend <- TRUE #last element
  comp_plots_p_final$x$data[[length(comp_plots_p_final$x$data)]]$name <- "WQ Threshold" 
}

comp_plots_p_final <- comp_plots_p_final %>% layout(legend = list(x = 0, y = -0.05, orientation = "h"))

##------------------------------------------------------------------------------
## Nutrients site comp setup
##------------------------------------------------------------------------------

char_list_n <- c("TN_mgL", "TP_ugL")

legend_list_n <- c(rep("none", length(char_list_n)-1), "bottom")

comp_plots_n <- purrr::map2(char_list_n, legend_list_n,
                         ~watersite_comps(netnwd, 
                                          year = params$current, 
                                          parkcode = params$park, 
                                          sitecode = site_list,
                                          charname = .x,
                                          legend = .y)) %>%
              set_names(char_list_n) #name plots to refer to them by char name

comp_plots_n_final <- subplot(comp_plots_n[1:length(comp_plots_n)],
                         titleY = TRUE, titleX = FALSE, margin = 0.05, nrows = 1) %>% 
                         #nrows = ifelse(length(comp_plots)> 4, 3, 2), 
                         #heights = if(length(char_list)>4) {c(0.3,0.35,0.3)}) %>%  
  style(showlegend = FALSE) %>% layout(autosize = FALSE, width = 900, height = 300)

num_sites <- c(1:length(site_names))

for (i in 1:length(num_sites)){
  comp_plots_n_final$x$data[[i]]$showlegend <- TRUE #first set of site elements 
  comp_plots_n_final$x$data[[length(comp_plots_n_final$x$data)]]$showlegend <- TRUE #last element
  comp_plots_n_final$x$data[[length(comp_plots_n_final$x$data)]]$name <- "WQ Threshold" 
}

comp_plots_n_final <- comp_plots_n_final %>% layout(legend = list(x = 0, y = -0.12, orientation = "h"))

```

# `r long_name` {.tabset .tabset-fade .tabset-pills}

```{r, p_site_comp, results = 'asis', include = show_comp}
##------------------------------------------------------------------------------
## Physical site comp plots                            
##------------------------------------------------------------------------------
cat("## ", "All Sites","{.tabset}", "\n")
if(params$nutrient==TRUE) {cat("### ", "Physical", "\n")}
cat("<h2>Monthly Water Quality Measurements", paste0("(", parkcode, " ", current, ")"),"</h2>")

fig_cap <- htmltools::withTags(body(
                          'The plots below compare monthly
                          measurements across all', long_name, 'sites during the',
                          current, 'field season. Only water quality parameters
                          that are measured at multiple sites are included. WQ thresholds
                          are derived from state surface water quality standards. See 
                          "About the Data" for more details.'))
cat(as.character(fig_cap))
```
```{r, p_site_comp_plots, results = 'show', out.height = "90%", eval = show_comp}
comp_plots_p_final

# Space between site comp chunks is necessary for tabset to work 
# (adding cat("\n") does not work)
```

```{r, n_site_comp, results = 'asis', include = show_comp}
##------------------------------------------------------------------------------
## Nutrient site comp plots                            
##------------------------------------------------------------------------------
if(params$nutrient==TRUE) {cat("### ", "Nutrients", "\n")}
if(params$nutrient==TRUE) {cat("<h2>Monthly Water Quality Measurements", paste0("(", parkcode, " ", current, ")"),"</h2>")}

fig_cap <- htmltools::withTags(body(
                          'The plots below compare monthly
                          measurements across all', long_name, 'sites during the',
                          current, 'field season. Only water quality parameters
                          that are measured at multiple sites are included. WQ thresholds
                          are derived from state surface water quality standards. See 
                          "About the Data" for more details.'))

if(params$nutrient==TRUE) {cat(as.character(fig_cap))}
```
```{r, n_site_comp_plots, results = 'show', out.height = "90%", eval = show_comp}
if(params$nutrient==TRUE) {comp_plots_n_final}
```

```{r, site_tab_setup, warning = F, message = F}
##------------------------------------------------------------------------------
## Physical site tab setup                            
##------------------------------------------------------------------------------
# create dataframe of physical parameters
char_list_p <- map(site_list, ~getCharInfo(netnwd, parkcode = params$park, sitecode = ., 
                             category = params$cat, info = "CharName")) %>%  
                 set_names(site_list) %>% unlist() %>% as.data.frame() 
                 #unlisting matches a site to each param

#reorganize dataframe                 
char_list_p$site_code <- substr(row.names(char_list_p), 1, 14) #select the site code
colnames(char_list_p) <- c("char_name", "site_code") #rename columns
rownames(char_list_p) <- c() #remove row names
site_char_list_p <- char_list_p[c("site_code", "char_name")] #rearrange column order

#iterate on dataframe to create waterbands plots
plot_list_p <- map2(site_char_list_p$site_code, site_char_list_p$char_name, 
                  ~waterbands(netnwd, parkcode = params$park, sitecode = .x, 
                              charname = .y, year_current = params$current,
                              year_historic = params$from, legend = "bottom")) %>% 
             set_names(site_char_list_p$site_code)

##------------------------------------------------------------------------------
## Nutrient site tab setup                            
##------------------------------------------------------------------------------
# LNETN target nutrients
stream_nutrients <- c("TP_ugL", "TN_mgL", "ANC_ueqL")
lake_nutrients <- c("TP_ugL", "TN_mgL", "ChlA_ugL")

# create list of all nutrient params per site
char_list_n <- map(site_list, ~getCharInfo(netnwd, parkcode = params$park, sitecode = ., 
                             category = "nutrients", info = "CharName")) %>%  
                 set_names(site_list) %>% unlist() %>% as.data.frame() 
                 #unlisting matches a site to each param

char_list_n$site_code <- substr(row.names(char_list_n), 1, 14) #select the site code
colnames(char_list_n) <- c("charname", "sitecode") #rename columns
rownames(char_list_n) <- c() #remove row names

# select target nutrients by site
site_char_list_n <- char_list_n[c("sitecode", "charname")] %>% 
  left_join(., site_key, by = c("sitecode"="Site")) %>% 
  filter((SiteType=="Lake" & charname %in% lake_nutrients) | (SiteType=="Stream" & charname %in% stream_nutrients))

#iterate on dataframe to create plots
plot_list_n <- map2(site_char_list_n$sitecode, site_char_list_n$charname, 
                  ~waterboxplot(sitecode=.x, charname=.y)) %>% 
                set_names(site_char_list_n$sitecode)

```

```{r site_tabs, warning = F, message = F, results='asis'}
##------------------------------------------------------------------------------
## Site tabs                           
##------------------------------------------------------------------------------

for(i in seq_along(site_list)){
  site <- site_list[i] # change back to i
  site_name <- getSiteInfo(netnwd, parkcode = params$park, sitecode = site, 
                          info = "SiteName")
  
  num_plots_p <- length(plot_list_p[names(plot_list_p) == site])
  num_plots_n <- length(plot_list_n[names(plot_list_n) == site])
  
  plot_title <- htmltools::withTags(h2('Historic', paste0('(',from, '–', to,')'),
                                                'vs. Current', paste0('(',current,')'), 'Measurements'))
                                                 
  fig_cap_p <- htmltools::withTags(body('The plots below show historic ranges
                                        for', site_name, 'based on the range of measurements collected from',
                                        from, 'to', to, 'for each month. The outermost band represents the
                                        historic maximum and minimum value collected for each month.
                                        The second inner band represents the 95% range of historic values
                                        by month. The innermost band represents the 50% range of historic
                                        values by month. The points in the figures represent the most recent
                                        measurements collected in', current, 'by month. WQ thresholds
                                        are derived from state surface water quality standards. See 
                                        "About the Data" for more details.'))
  
  fig_cap_n <- htmltools::withTags(body('Placeholder for nutrient plot caption.'))
  
  fig_height_p <- ifelse(num_plots_p > 4, 6.5, 4.5)
  fig_height_n <- ifelse(num_plots_n > 4, 6.5, 4.5)
  fig_width <- 9.3
  
  subplots_p <- subplot(plot_list_p[names(plot_list_p) == site][1:num_plots_p],
                      titleY = TRUE, titleX = FALSE, margin = 0.05,
                      nrows = ifelse(num_plots_p>4, 3, 2),
                      #heights = ifelse(num_plots_p>4, c(0.3, 0.35, 0.3), c(0.3, 0.3))) %>% 
                      heights = if(num_plots_p>4) {c(0.3,0.35,0.3)}) %>% 
             #style(showlegend = FALSE) %>% 
             layout(legend = list(x = 0, y = ifelse(num_plots_p>4, -0.05, -0.08),
                                  orientation = "h"))
  
  subplots_n <- subplot(plot_list_n[names(plot_list_n) == site][1:num_plots_n],
                      titleY = TRUE, titleX = FALSE, margin = 0.05,
                      nrows = ifelse(num_plots_n>4, 3, 2),
                      #heights = ifelse(num_plots_n>4, c(0.3, 0.35, 0.3), c(0.3, 0.3)),
                      #heights = if(num_plots_n>4) {c(0.3,0.35,0.3)}, 
                      which_layout = 1) %>% 
             #style(showlegend = FALSE) #%>% 
             layout(legend = list(x = 0, y = ifelse(num_plots_n>4, -0.05, -0.08),
                                  orientation = "h"))

##------------------------------------------------------------------------------
## Legend - physical                           
##------------------------------------------------------------------------------
  # Logical way to find and turn on poor water quality and wq thresholds
  # First turn them all off
  for (i in seq(1:length(subplots_p$x$data))) {
    subplots_p$x$data[[i]]$showlegend <- FALSE
  }
  
  # Find the first time the poor water quality point is used- returns the index number
  find_pwq <- data.frame(pwq = lapply(seq_along(subplots_p$x$data), 
    function(i){
      if(subplots_p$x$data[[i]]$name == "orange"){paste0(i)
        } else{NA}}) %>% 
      unlist()) %>% na.omit() %>% slice(1) %>% as.numeric()
  
  # Find the first time the water quality threshold is used- returns the index number
  find_wqt <- data.frame(wqt = lapply(seq_along(subplots_p$x$data),
    function(i){
      if(!is.null(subplots_p$x$data[[i]]$line$dash)){
      if(subplots_p$x$data[[i]]$line$dash == "dash"){
        paste0(i)
        } else{NA}}
        else{NA}
      } ) %>% unlist()) %>%
      na.omit() %>% slice(1) %>% as.numeric()
  
  # Turn on the legends that never change
  subplots_p$x$data[[2]]$showlegend <- TRUE
  subplots_p$x$data[[2]]$name = "Historic range"
  subplots_p$x$data[[5]]$showlegend <- TRUE
  subplots_p$x$data[[5]]$name = "Historic 95% range"
  subplots_p$x$data[[8]]$showlegend <- TRUE
  subplots_p$x$data[[8]]$name = "Historic 50% range"
  subplots_p$x$data[[11]]$showlegend <- TRUE
  subplots_p$x$data[[11]]$name = "Historic median"
  subplots_p$x$data[[12]]$showlegend <- TRUE
  subplots_p$x$data[[12]]$name = "Current value"
  
  # Turn on the poor water quality and thresholds if they existed
  if(!is.na(find_pwq)){
    subplots_p$x$data[[find_pwq]]$showlegend <- TRUE
    subplots_p$x$data[[find_pwq]]$name <- "Poor WQ value"}
  
  if(!is.na(find_wqt)){
    subplots_p$x$data[[find_wqt]]$showlegend <- TRUE
    subplots_p$x$data[[find_wqt]]$name <- "WQ threshold"}
  
##------------------------------------------------------------------------------
## Legend - nutrients                           
##------------------------------------------------------------------------------
  # Logical way to find and turn on poor water quality and wq thresholds
  # First turn them all off
  for (i in seq(1:length(subplots_n$x$data))) {
    subplots_n$x$data[[i]]$showlegend <- FALSE
  }
  
  # Find the first time the historic range is used- returns the index number
  find_hstr <- data.frame(hstr = lapply(seq_along(subplots_n$x$data),
    function(i){
      if(subplots_n$x$data[[i]]$name == "Historic range"){
        paste0(i)
        } else{NA}
      } ) %>% unlist()) %>%
      na.omit() %>% slice(1) %>% as.numeric()
  
   # Find the first time the current value is used- returns the index number
  find_ctv <- data.frame(ctv = lapply(seq_along(subplots_n$x$data),
    function(i){
      # Check that the point has a y value (exists on the plot)
      y_check <- grepl("y",subplots_n$x$data[[i]]$y, fixed=TRUE) %>% unique()
      if(subplots_n$x$data[[i]]$name == "Current value" & y_check==FALSE){paste0(i)
        } else{NA}
      } ) %>% unlist()) %>%
      na.omit() %>% slice(1) %>% as.numeric()
  
  # Find the first time the poor water quality point is used- returns the index number
  find_pwq <- data.frame(pwq = lapply(seq_along(subplots_n$x$data),
    function(i){
      # Check that the point has a y value (exists on the plot)
      y_check <- grepl("y",subplots_n$x$data[[i]]$y, fixed=TRUE) %>% unique()
      if(subplots_n$x$data[[i]]$name == "Poor WQ value" & y_check==FALSE){paste0(i)
        } else{NA}}) %>%
      unlist()) %>% na.omit() %>% slice(1) %>% as.numeric()

  # Find the first time the water quality threshold is used- returns the index number
  find_wqt <- data.frame(wqt = lapply(seq_along(subplots_n$x$data),
    function(i){
      if(subplots_n$x$data[[i]]$name == "WQ threshold"){
        paste0(i)
        } else{NA}
      } ) %>% unlist()) %>%
      na.omit() %>% slice(1) %>% as.numeric()

  # Turn on the poor water quality and thresholds if they existed
  if(!is.na(find_hstr)){
    subplots_n$x$data[[find_hstr]]$showlegend <- TRUE
    }
  
  if(!is.na(find_ctv)){
    subplots_n$x$data[[find_ctv]]$showlegend <- TRUE
    }
  
  if(!is.na(find_pwq)){
    subplots_n$x$data[[find_pwq]]$showlegend <- TRUE
    }

  if(!is.na(find_wqt)){
    subplots_n$x$data[[find_wqt]]$showlegend <- TRUE
    }

  test <- htmltools::withTags(body('test comment'))
  
##------------------------------------------------------------------------------
## Knit tabs                           
##------------------------------------------------------------------------------
  
  # Unique chunk labels
  site_n <- paste0(site, '_n')
  site_p <- paste0(site, '_p')
  
  # Create tab chunk templates
    if(params$nutrient == FALSE) {
    template <- paste0(
      "## {{site_name}}\n",
      "```{r {{site}}, fig.height=",fig_height_p, ", fig.width=", fig_width,", echo = FALSE}\n",
      "plot_title\n",
      "\n",
      "fig_cap_p\n",
      "subplots_p\n",
      "```\n",
      "\n"
  )
} else {template <- paste0(
      "## {{site_name}}{.tabset}\n",
      "### Physical\n",
      "```{r {{site_p}}, fig.height=",fig_height_p, ", fig.width=", fig_width,", echo = FALSE}\n",
      "plot_title\n",
      "\n",
      "fig_cap_p\n",
      "subplots_p\n",
      "```\n",
      "\n",
      "### Nutrients\n",
      "```{r {{site_n}}, fig.height=",fig_height_n, ", fig.width=", fig_width,", echo = FALSE}\n",
      "plot_title\n",
      "\n",
      "fig_cap_n\n",
      "subplots_n\n",
      "```\n",
      "\n"
  )
}
  
  # expand expressions within {{ }}
  tab <- knitr::knit_expand(text = template)
  
  # knit results
  cat(knitr::knit(text = unlist(tab), quiet = TRUE))
  
}

```

## About the Sites
```{r, leaflet, out.width="100%", message=F}

source("../scripts/leaflet_tile_urls.R")
bbox <- read.csv("../boundboxes.csv")  
site_csv <- read.csv(file = '../SiteInfo.csv')

long_cent <- mean(c(bbox$LongE[bbox$ParkCode == params$park], bbox$LongW[bbox$ParkCode == params$park]))
lat_cent <- mean(c(bbox$LatN[bbox$ParkCode == params$park], bbox$LatS[bbox$ParkCode == params$park]))

years_active <- getWData(netnwd, parkcode = params$park, category = params$cat) %>% 
 group_by(Site) %>%
 summarize(start_date = format(min(Date), "%b %Y"),
 last_date = format(max(Date), "%b %Y")) %>%
 ungroup()

water_sites <- data.frame(ParkCode = getSiteInfo(netnwd, parkcode = params$park, info = "ParkCode"),       
                          SiteCode = getSiteInfo(netnwd, parkcode = params$park, info = "SiteCode"),
                          SiteName = getSiteInfo(netnwd, parkcode = params$park, info = "SiteName"), 
                          lat = getSiteInfo(netnwd, parkcode = params$park, info = "lat"),          
                          long = getSiteInfo(netnwd, parkcode = params$park, info = "long"),
                          type = getSiteInfo(netnwd, parkcode = params$park, info = "type")) %>% 
  left_join(years_active, by = c("SiteCode" = "Site")) %>% 
  left_join(site_csv, by = c("SiteCode", "ParkCode", "SiteName")) %>% 
  mutate(Link = paste0("<a href='https://doimspp.sharepoint.com/sites/NETN_Photo_Viewer/Water_Quality_Site_Photos/", 
                       .$SiteCode, ".jpg' target='_blank'>Site Photo</a>"))

# Legend html generator
markerLegendHTML <- function(IconSet) {
    # container div
    legendHtml <- "<div style='padding: 10px; padding-bottom: 10px;'>
    <h4 style='padding-top:0; padding-bottom:10px; margin: 0; color:#555'> Legend </h4>"

    n <- 1
    # add each icon for ion library icons:
    for (Icon in IconSet) {
        if (Icon[["library"]] == "ion") {
        legendHtml<- paste0(legendHtml, "<div style='width: auto; height: 45px; display: flex; align-items: center;'>",
                             "<div style='position: relative; display: inline-block; width: 35px; height: 45px;' 
                               class='awesome-marker-icon-",Icon[["markerColor"]]," awesome-marker'>",
                               "<i style='margin-left: 4px; margin-top: 11px' class= 'ion ion-",Icon[["icon"]]," icon-",Icon[["iconColor"]],"'></i>",
                             "</div>",
                             "<div style='position: relative; display: inline-block; margin-left: 8px;'>", names(IconSet)[n] ,"</div>",
                           "</div>")    
        }
        n <- n + 1
    } 
    paste0(legendHtml, "</div>")
}

IconSet <- awesomeIconList(
  "Stream" = makeAwesomeIcon(icon= 'waterdrop', markerColor = 'blue', iconColor = 'white', library = "ion"),
  "Lake" = makeAwesomeIcon(icon= 'waterdrop', markerColor = 'cadetblue', iconColor = 'white', library = "ion")
)

leaflet() %>%
    setView(lng = long_cent,
            lat = lat_cent,
            zoom = bbox$Zoom[bbox$ParkCode == params$park]) %>%
    # setMaxBounds(lng1 = bbox[bbox$ParkCode == params$park,]$LongE,
    #              lng2 = bbox[bbox$ParkCode == params$park,]$LongW,
    #              lat1 = bbox[bbox$ParkCode == params$park,]$LatN,
    #              lat2 = bbox[bbox$ParkCode == params$park,]$LatS) %>%
    addTiles(group="Map", urlTemplate = NPSbasic, attribution = NPSAttrib,
             options = providerTileOptions(minZoom = bbox$minZoom[bbox$ParkCode == params$park])) %>%
    addTiles(group="Imagery", urlTemplate = NPSimagery, attribution=NPSAttrib) %>%
    addTiles(group="Light", urlTemplate = NPSlight, attribution = NPSAttrib) %>%
    addTiles(group="Slate", urlTemplate = NPSslate, attribution = NPSAttrib) %>%
    addLayersControl(map = ., baseGroups = c("Map","Imagery","Light", "Slate"),
                     options = layersControlOptions(collapsed=T)) %>%
    addAwesomeMarkers(data = water_sites, ~long, ~lat, icon= ~IconSet[type],
                      label=as.character(water_sites$SiteName),
                      popup = paste0("<b>", water_sites$SiteName, "</b><br>",
                                     "<b>Type: </b>", water_sites$type, "<br>",
                                     "<b>Sample Period: </b>", water_sites$start_date, "&ndash;", water_sites$last_date, "<br>",
                                     water_sites$Description, "<br>",
                                     water_sites$Link
                                     )
                      ) %>%
    addControl(markerLegendHTML(IconSet = IconSet), position = "bottomleft")

```
```{r site_info, results = 'asis'}

# option 2: site descriptions below map
# for (i in site_list){
#   # split because the cat didn't work with multiple items
#   htmltools::h4(getSiteInfo(netnwd, park = params$park, sitecode = i, info = "SiteName")) %>% 
#     as.character() %>% 
#     cat()
#   
#   site_info <- site_csv$Description[site_csv$SiteCode == i] 
#   htmltools::withTags(body(site_info)) %>% 
#     as.character() %>% 
#     cat()
# }

```

```{r About_tabs, child = "About_tabs_20210113_kmm.Rmd"}

```


