---
output: 
  html_document:
    fig_caption: yes
    css: stylesheets/custom_styles.css
    anchor_sections: FALSE
    includes: 
      in_header: "header_manual.html" 
      after_body: "footer.html"
params:
  park: MABI
  from: 2006
  to: 2018
  current: 2019
  cat: nutrients
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.pos = "h")
```

```{r libs, include = FALSE, results = 'hide'}
library(NCRNWater)
library(tidyverse)
library(plotly)
library(purrr)
library(htmltools)
library(leaflet)
library(viridis)
library(kableExtra)
```

```{r import}
path = "C:/Users/Diana/Documents/NETN/Water/data"
#path = "D:/NETN/R_Dev/Water/NCRNWaterViz/Data/NETN"
netnwd <- importNCRNWater(Dir = path, 
                          Data = "Water Data.csv", 
                          MetaData = "VizMetaData.csv")

```
```{r globvars, message = F}
# Variables for cat asis code, which can't take params
parkcode = params$park
current = params$current
from = params$from
to = params$to
category = params$cat

# Long park name
long_name = getParkInfo(netnwd, park = params$park, info = "ParkLongName")

# List of sites
site_list_all <- getSiteInfo(netnwd, park = params$park, info = "SiteCode")
sites_curr <- getWData(netnwd, park = params$park, years = params$current) %>% 
                select(Site) %>% unique()

#Set up site_list so only includes sites sampled in current year
site_list <- site_list_all[site_list_all %in% sites_curr$Site] 

show_comp <- ifelse(length(site_list) > 1, TRUE, FALSE)

```

```{r nutrient_test, warning = F, message = F, eval = F}
char_list <- map(site_list, ~getCharInfo(netnwd, parkcode = params$park, sitecode = ., 
                             category = params$cat, info = "CharName")) %>%  
                 set_names(site_list) %>% unlist() %>% as.data.frame() 
                 #unlisting matches a site to each param

wdat <- getWData(netnwd, park = params$park, category = params$cat) 

char <- wdat %>% 
  filter(Characteristic == "DOC_mgL")
char$Year <- format(as.Date(char$Date), "%Y")

# plotly_fig <- plot_ly(total_N, x = ~Year, y = ~ValueCen, type = "box")
# 
# plotly_fig

ggplot_fig <- ggplot(char, aes(x=Year, y=ValueCen)) +
  geom_boxplot(color="#1378b5", fill="#76b4db", alpha = 0.85,
                outlier.color = "orange") +
  geom_point() +
  #scale_y_continuous(breaks = seq(0, max(char$ValueCen), by=0.1)) +
  #geom_dotplot(binaxis="y", stackdir="center") +
  forestMIDN::theme_FVM()

ggplotly(ggplot_fig)

```

# `r long_name` {.tabset .tabset-fade .tabset-pills}

``` {r boxplot_function, warning=F, message=F}

sitecode = "NETN_MABI_SA00"
charname = "TN_mgL"

# by month
boxplot_monthly <- function(sitecode, charname) {
  
  wdat <- getWData(netnwd, parkcode = params$park, sitecode = sitecode, 
                                 charname = charname, category = params$cat,
                                 years = params$from:params$current)
  
  # Add months and censored info for later filter for plotting
  wdat <- wdat %>% mutate(month = lubridate::month(Date, label = TRUE, abbr = TRUE),
                          month_num = as.numeric(month),
                          year = lubridate::year(Date)) %>% 
              #filter(between(month_num, min(months), max(months))) %>% 
                   arrange(Date)
  
  wdat_hist <- wdat[wdat$year < params$current, ] 
  wdat_curr <- wdat[wdat$year == params$current, ]
  
  # Create y axis label with units in parentheses, unless it's pH (no units)
  ylabel <- getCharInfo(netnwd, parkcode = params$park, sitecode = sitecode, charname = charname,
                        info = "CategoryDisplay")# %>% 
    #ifelse(. != "pH", paste0(.," (", unit, ")"), .)
  
  ggplot_fig <- ggplot(wdat, aes(x=month, y=ValueCen)) +
    geom_boxplot(color="#1378b5", fill="#76b4db", alpha = 0.85,
                outlier.color = "orange") +
    geom_point(size=0.7) +
  
    #scale_y_continuous(breaks = seq(0, max(char$ValueCen), by=0.1)) +
    #geom_dotplot(binaxis="y", stackdir="center") +
    forestMIDN::theme_FVM() +
    theme(axis.text.x = element_text(angle = 45)) +
    labs(y = ylabel, x = NULL)

return(ggplotly(ggplot_fig))
  
}

# by year
boxplot_annual <- function(sitecode, charname) {
  
  wdat <- getWData(netnwd, park = params$park, category = params$cat) %>% 
    filter(Characteristic == char_name) 
    wdat$Year <- format(as.Date(wdat$Date), "%Y")
    
  # Create y axis label with units in parentheses, unless it's pH (no units)
  ylabel <- getCharInfo(netnwd, parkcode = params$park, sitecode = sitecode, charname = charname,
                        info = "CategoryDisplay")# %>% 
    #ifelse(. != "pH", paste0(.," (", unit, ")"), .)
    
  ggplot_fig <- ggplot(wdat, aes(x=Year, y=ValueCen)) +
    geom_boxplot(color="#1378b5", fill="#76b4db", alpha = 0.85,
                outlier.color = "orange") +
    geom_point(size=0.7) +
  
    #scale_y_continuous(breaks = seq(0, max(char$ValueCen), by=0.1)) +
    #geom_dotplot(binaxis="y", stackdir="center") +
    forestMIDN::theme_FVM() +
    theme(axis.text.x = element_text(angle = 45)) +
    labs(y = ylabel, x = NULL)

return(ggplotly(ggplot_fig))
  
}

```

```{r, site_tab_setup, warning = F, message = F}

char_list <- map(site_list, ~getCharInfo(netnwd, parkcode = params$park, sitecode = ., 
                             category = params$cat, info = "CharName")) %>%  
                 set_names(site_list) %>% unlist() %>% as.data.frame() 
                 #unlisting matches a site to each param

#reorganize dataframe                 
char_list$site_code <- substr(row.names(char_list), 1, 14) #select the site code
colnames(char_list) <- c("charname", "sitecode") #rename columns
rownames(char_list) <- c() #remove row names
site_char_list <- char_list[c("sitecode", "charname")] #rearrange column order

#iterate on dataframe to create boxplots
plot_list <- map2(site_char_list$sitecode, site_char_list$charname, 
                  ~boxplot_monthly(sitecode=.x, charname=.y)) %>% 
             set_names(site_char_list$sitecode)

```

```{r site_tabs, warning = F, message = F, results='asis'}

for(i in seq_along(site_list)){
  site <- site_list[i]
  site_name <- getSiteInfo(netnwd, parkcode = params$park, sitecode = site, 
                          info = "SiteName")
  num_plots <- length(plot_list[names(plot_list) == site])
  
  plot_title <- htmltools::withTags(h2('Insert title'))
                                                 
  fig_cap <- htmltools::withTags(body('Nutrient caption goes here.'))
  
  fig_height <- ifelse(num_plots > 4, 6.5, 4.5)
  fig_width <- 9.3
  
  subplots <- subplot(plot_list[names(plot_list) == site][1:num_plots],
                      titleY = TRUE, titleX = FALSE, margin = 0.05,
                      nrows = ifelse(num_plots>4, 3, 2),
                      #heights = ifelse(num_plots>4, c(0.3, 0.35, 0.3), c(0.3, 0.3))) %>% 
                      heights = if(num_plots>4) {c(0.3,0.35,0.3)}) %>% 
             #style(showlegend = FALSE) %>% 
             layout(legend = list(x = 0, y = ifelse(num_plots>4, -0.05, -0.08),
                                  orientation = "h"))
  
  # # Logical way to find and turn on poor water quality and wq thresholds
  # # First turn them all off
  # for (i in seq(1:length(subplots$x$data))) {
  #   subplots$x$data[[i]]$showlegend <- FALSE
  # }
  # 
  # # Find the first time the poor water quality point is used- returns the index number
  # find_pwq <- data.frame(pwq = lapply(seq_along(subplots$x$data), 
  #   function(i){
  #     if(subplots$x$data[[i]]$name == "orange"){paste0(i)
  #       } else{NA}}) %>% 
  #     unlist()) %>% na.omit() %>% slice(1) %>% as.numeric()
  # 
  # # Find the first time the water quality threshold is used- returns the index number
  # find_wqt <- data.frame(wqt = lapply(seq_along(subplots$x$data),
  #   function(i){
  #     if(!is.null(subplots$x$data[[i]]$line$dash)){
  #     if(subplots$x$data[[i]]$line$dash == "dash"){
  #       paste0(i)
  #       } else{NA}}
  #       else{NA}
  #     } ) %>% unlist()) %>%
  #     na.omit() %>% slice(1) %>% as.numeric()
  # 
  # # Turn on the legends that never change
  # subplots$x$data[[2]]$showlegend <- TRUE
  # subplots$x$data[[2]]$name = "Historic range"
  # subplots$x$data[[5]]$showlegend <- TRUE
  # subplots$x$data[[5]]$name = "Historic 95% range"
  # subplots$x$data[[8]]$showlegend <- TRUE
  # subplots$x$data[[8]]$name = "Historic 50% range"
  # subplots$x$data[[11]]$showlegend <- TRUE
  # subplots$x$data[[11]]$name = "Historic median"
  # subplots$x$data[[12]]$showlegend <- TRUE
  # subplots$x$data[[12]]$name = "Current value"
  # 
  # # Turn on the poor water quality and thresholds if they existed
  # if(!is.na(find_pwq)){
  #   subplots$x$data[[find_pwq]]$showlegend <- TRUE
  #   subplots$x$data[[find_pwq]]$name <- "Poor WQ value"}
  # 
  # if(!is.na(find_wqt)){
  #   subplots$x$data[[find_wqt]]$showlegend <- TRUE
  #   subplots$x$data[[find_wqt]]$name <- "WQ threshold"}

  template <- paste0(
    "## {{site_name}}\n",
    "```{r {{site}}, fig.height=",fig_height, ", fig.width=", fig_width,", echo = FALSE}\n",
    "plot_title\n",
    "\n",
    "fig_cap\n",
    "subplots\n",
    "```\n",
    "\n"
  )
  
  # expand expressions within {{ }}
  tab <- knitr::knit_expand(text = template)
  
  # knit results
  cat(knitr::knit(text = unlist(tab), quiet = TRUE))
  
}

```



