---
output: 
  html_document:
    fig_caption: yes
    css: stylesheets/custom_styles.css
    anchor_sections: FALSE
    includes: 
      in_header: "header_manual.html" 
      after_body: "footer.html"
params:
  park: MABI
  from: 2006
  to: 2018
  current: 2019
  cat: nutrients
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.pos = "h")
```

```{r libs, include = FALSE, results = 'hide'}
library(NCRNWater)
library(tidyverse)
library(plotly)
library(purrr)
library(htmltools)
library(leaflet)
library(viridis)
library(kableExtra)
```

```{r import}
path = "C:/Users/Diana/Documents/NETN/Water/data"
#path = "D:/NETN/R_Dev/Water/NCRNWaterViz/Data/NETN"
netnwd <- importNCRNWater(Dir = path, 
                          Data = "Water Data.csv", 
                          MetaData = "VizMetaData.csv")

```
```{r globvars, message = F}
# Variables for cat asis code, which can't take params
parkcode = params$park
current = params$current
from = params$from
to = params$to
category = params$cat

# Long park name
long_name = getParkInfo(netnwd, park = params$park, info = "ParkLongName")

# List of sites
site_list_all <- getSiteInfo(netnwd, park = params$park, info = "SiteCode")
sites_curr <- getWData(netnwd, park = params$park, years = params$current) %>% 
                select(Site) %>% unique()

#Set up site_list so only includes sites sampled in current year
site_list <- site_list_all[site_list_all %in% sites_curr$Site] 

# Create site key for sitecode and type
site_key <- data.frame(Site = getSiteInfo(netnwd, parkcode = parkcode, info = "SiteCode"),
                         SiteType =  getSiteInfo(netnwd, parkcode = parkcode, info = "type"))

show_comp <- ifelse(length(site_list) > 1, TRUE, FALSE)

```

# `r long_name` {.tabset .tabset-fade .tabset-pills}

```{r boxplot_function, warning=F, message=F}

# #params for building package function
# sitecode <- site_list[1]
# charname <- "TN_mgL"

waterboxplot <- function(sitecode, charname) {

  # params for package function
  parkcode <- params$park
  category <- params$cat
  object <- netnwd
  assessment <- TRUE # function param for assessment line
  
  # Compile water data for target years (from - current) and add columns for month, 
  # historical and current year data, upper and lower assessment, and outlier color
  wdat <- getWData(object, parkcode = parkcode, sitecode = sitecode, 
                                   charname = charname, category = category,
                                   years = params$from:params$current) %>% 
          mutate(month = lubridate::month(Date, label = TRUE, abbr = TRUE), 
                 month_num = as.numeric(month), 
                 year = lubridate::year(Date),
                 ValueCen_curr = ifelse(year == params$current, ValueCen, NA),
                 ValueCen_hist = ifelse(year != params$current, ValueCen, NA),
                 LowerPoint = ifelse(assessment == TRUE, 
                                     getCharInfo(object, parkcode = parkcode, sitecode = sitecode, 
                                                         charname = charname, category = category, 
                                                         info = "LowerPoint"), NA),
                 UpperPoint = ifelse(assessment == TRUE, 
                                     getCharInfo(object, parkcode = parkcode, sitecode = sitecode, 
                                                         charname = charname, category = category, 
                                                         info = "UpperPoint"), NA),
                 pcolor = ifelse(!is.na(UpperPoint) & ValueCen_curr > UpperPoint, "orange",
                          ifelse(!is.na(LowerPoint) & ValueCen_curr < LowerPoint, "orange", "black"))) %>% 
          arrange(Date) %>% 
          left_join(., site_key, by = "Site")
  
  # Filter target months based on site type
  # note: this may have problems later if target months are different
  if (all(wdat$SiteType == "Lake")) {
    wdat <- filter(wdat, month == "Jun" | month == "Aug")} else {
       wdat <- filter(wdat, month == "May" | month == "Aug")
    }
  
  wdat_curr <- wdat %>% filter(year == params$current)
  
  param_name <- getCharInfo(object, parkcode = parkcode, sitecode = sitecode,
                            charname = charname, info = "CategoryDisplay") %>% unique()

  unit <- getCharInfo(object, parkcode = parkcode, sitecode = sitecode, 
                      charname = charname, info = "Units") %>% unique()

  yname <- ifelse(charname != "pH", 
                  paste0(getCharInfo(object, parkcode = parkcode, sitecode = sitecode,
                                     charname = charname, info = "CategoryDisplay") %>% unique(), " (", 
                         getCharInfo(object, parkcode = parkcode, sitecode = sitecode,
                                     charname = charname, info = "Units") %>% unique(),                           
                         ")"),
                  paste0(getCharInfo(object, parkcode = parkcode, sitecode = sitecode,
                                     charname = charname, info = "CategoryDisplay") %>% unique()))
  
  # Create boxplot with historic data and overlay target year measurements
  p <- ggplot(wdat, aes(x=month, y=ValueCen_hist)) +
       geom_boxplot(color="#1378b5", fill="#76b4db", alpha = 0.85) +
       # geom_point(aes(y=ValueCen_curr, color = pcolor, fill = pcolor,
       #            text = paste0(month, " ", params$current, "<br>",
       #            param_name, ": ", round(ValueCen_curr, 1), " ", unit)),
       #            color = wdat$pcolor, fill = wdat$pcolor, shape = 21) +
       geom_point(data = wdat_curr,
                   aes(y=ValueCen_curr, color = pcolor, fill = pcolor,
                   text = paste0(month, " ", params$current, "<br>",
                   param_name, ": ", round(ValueCen_curr, 1), " ", unit)),
                   color = wdat_curr$pcolor, fill = wdat_curr$pcolor, shape = 21)+
       # Upper and lower assessment lines
       {if(assessment == TRUE)
         geom_hline(aes(yintercept = LowerPoint, linetype="legend", text = paste("Lower", param_name, "threshold:", LowerPoint, unit)),
                        #linetype = "dashed", color = "#212121")}+
                        color = "#212121")}+
       {if(assessment == TRUE)
         geom_hline(aes(yintercept = UpperPoint, text = paste("Upper", param_name, "threshold:", UpperPoint, unit)),
                      linetype = "dashed", color = "#212121")}+
       forestMIDN::theme_FVM() +
       theme(legend.position="bottom")+
       labs(y = yname, x = NULL) 
  
  p <- ggplotly(p, tooltip = "text", showlegend=TRUE)
  
  # plotly makes two types of outliers that are controlled via different traces
  p$x$data[[1]]$marker$symbol = "asterisk" # this changes all outliers to asterisks
  # change color and size of first set (not as extreme outliers)
  p$x$data[[1]]$marker$outliercolor = "#1378b5"
  p$x$data[[1]]$marker$size = 7
  # change color and size of second set (extreme outliers)
  p$x$data[[1]]$marker$line$color = "#1378b5"
  p$x$data[[1]]$marker$line$width = 1
    
  # p$x$data[[2]]$marker$color[1] <- "black"
  # p$x$data[[2]]$marker$color[2] <- "orange"
  # p$x$data[[2]]$marker$line$color[1] <- "black"
  # p$x$data[[2]]$marker$line$color[2] <- "orange"

  return(p)

  }
  
#----Unused plotly marker code----  
  # hardcoded marker color changes
  # p$x$data[[2]]$marker$color = "rgba(0,0,0,1)"
  # p$x$data[[2]]$marker$line$color = "rgba(0,0,0,1)"
  # p$x$data[[3]]$marker$color = "rgba(254,177,177,1)"
  # p$x$data[[3]]$marker$line$color = "rgba(254,177,177,1)"
  
#   for (i in 1:length(p$x$data)){
#     if(p$x$data[[i]]$name == "orange") {p$x$data[[i]]$marker$color = "rgba(254,177,177,1)"
#     } else{
#         if(p$x$data[[i]]$name == "black") {p$x$data[[i]]$marker$color = "rgba(0,0,0,1)"
#           } else{NA}
#       }
# }
  
  
  # reassign marker colors since plotly does not read pcolor correctly
  # fix_pcolor <- data.frame(fpc = lapply(seq_along(p$x$data), 
  #   function(i){
  #     if(p$x$data[[i]]$name == "orange"){p$x$data[[i]]$marker$color == "orange"
  #     #if(subplots$x$data[[i]]$marker$color == "rgba(255,165,0,1)"){paste0(i)
  #       } else{
  #         if(p$x$data[[i]]$name == "black"){p$x$data[[i]]$marker$color == "black"
  #         } else{NA}
  #         }})) 
  
  # # overrides black outline of outliers
  # p$x$data[[1]]$marker$line$color = "rgba(0,0,0,0)"
  # # overrides black extreme outlier color
  # p$x$data[[1]]$marker$outliercolor = "rgba(0,0,0,0)"
  # # overrides black not as extreme outlier color
  # p$x$data[[1]]$marker$color = "rgba(0,0,0,0)"

  # p$x$data <- lapply(p$x$data, FUN = function(x){
  #     if (x$type == "box") {x$marker = list(opacity = 0)} else {NA}})
  
  # p$x$data <- lapply(p$x$data[2], FUN = function(x){
  #     x$marker = list(opacity = 0)
  #     return(x)})

  #plotly
  
  # plotly <- plotly %>% add_trace(data = wdat_curr, x = ~month, y = ~ValueCen, type = 'scatter',
  #           mode = "markers", marker = list(color = "black"))
  
  # plotly_fig <- plot_ly(wdat_hist, x = ~month, y = ~ValueCen, type = "box") %>% 
  #   add_trace(data = wdat_curr, x = ~month, y = ~ValueCen, type = 'scatter',
  #           mode = "markers", marker = list(color = "black"))
  
```

```{r site_tab_setup, warning = F, message = F, eval = T}

# stream_nutrients <- c("TP_ugL", "TN_mgL", "ANC_ueqL")
# lake_nutrients <- c("TP_ugL", "TN_mgL", "ChlA_ugL")
# 
# nutrient_join <- data.frame(SiteType = rep(c("Lake", "Stream"), each = 3),
# nutrients = c(lake_nutrients, stream_nutrients))
# nutrient_join
# 
# # create list of all nutrient params per site
# char_list <- map(site_list, ~getCharInfo(netnwd, parkcode = params$park, sitecode = .,
# category = params$cat, info = "CharName")) %>%
# set_names(site_list) %>% unlist() %>% as.data.frame()
# #unlisting matches a site to each param
# char_list$site_code <- substr(row.names(char_list), 1, 14) #select the site code
# colnames(char_list) <- c("charname", "sitecode") #rename columns
# rownames(char_list) <- c() #remove row names
# 
# site_key <- data.frame(Site = getSiteInfo(netnwd, parkcode = parkcode, info = "SiteCode"),
# SiteType = getSiteInfo(netnwd, parkcode = parkcode, info = "type"))
# 
# site_char_list <- char_list[c("sitecode", "charname")] %>% #rearrange column order
# left_join(., site_key, by = c("sitecode"="Site")) %>%
# left_join(nutrient_join, ., by = "SiteType")
# 
# site_char_list <- char_list[c("sitecode", "charname")] %>% #rearrange column order
# left_join(., site_key, by = c("sitecode"="Site")) %>%
# left_join(nutrient_join, ., by = "SiteType") %>%
# filter(!is.na(sitecode))

# LNETN target nutrients
stream_nutrients <- c("TP_ugL", "TN_mgL", "ANC_ueqL")
lake_nutrients <- c("TP_ugL", "TN_mgL", "ChlA_ugL")

# create list of all nutrient params per site
char_list <- map(site_list, ~getCharInfo(netnwd, parkcode = params$park, sitecode = ., 
                             category = params$cat, info = "CharName")) %>%  
                 set_names(site_list) %>% unlist() %>% as.data.frame() 
                 #unlisting matches a site to each param
char_list$site_code <- substr(row.names(char_list), 1, 14) #select the site code
colnames(char_list) <- c("charname", "sitecode") #rename columns
rownames(char_list) <- c() #remove row names

# select target nutrients by site
site_char_list <- char_list[c("sitecode", "charname")] %>% 
  left_join(., site_key, by = c("sitecode"="Site")) %>% 
  filter((SiteType=="Lake" & charname %in% lake_nutrients) | (SiteType=="Stream" & charname %in% stream_nutrients))

#iterate on dataframe to create plots
plot_list <- map2(site_char_list$sitecode, site_char_list$charname, 
                  ~waterboxplot(sitecode=.x, charname=.y)) %>% 
                set_names(site_char_list$sitecode)

```

```{r, site_comp_setup, echo = F, warning = F, message = F, eval = show_comp}
site_names <- getSiteInfo(netnwd, park = params$park, sitecode = site_list, info = "SiteName")

# char_list <- getCharInfo(netnwd, parkcode = params$park, category = params$cat,
#                          info = "CharName") %>% #.[duplicated(.)] %>%
#                          unique() %>%
#   .[. != "DOC_mgL"]

char_list <- c("TN_mgL", "TP_ugL")

legend_list <- c(rep("none", length(char_list)-1), "bottom")

comp_plots <- purrr::map2(char_list, legend_list,
                         ~watersite_comps(netnwd, 
                                          year = params$current, 
                                          parkcode = params$park, 
                                          sitecode = site_list,
                                          charname = .x,
                                          legend = .y)) %>%
              set_names(char_list) #name plots to refer to them by char name

comp_plots_final <- subplot(comp_plots[1:length(comp_plots)],
                         titleY = TRUE, titleX = FALSE, margin = 0.05, nrows = 1) %>% 
                         #nrows = ifelse(length(comp_plots)> 4, 3, 2), 
                         #heights = if(length(char_list)>4) {c(0.3,0.35,0.3)}) %>%  
  style(showlegend = FALSE) %>% layout(autosize = FALSE, width = 900, height = 300)

num_sites <- c(1:length(site_names))

for (i in 1:length(num_sites)){
  comp_plots_final$x$data[[i]]$showlegend <- TRUE #first set of site elements 
  comp_plots_final$x$data[[length(comp_plots_final$x$data)]]$showlegend <- TRUE #last element
  comp_plots_final$x$data[[length(comp_plots_final$x$data)]]$name <- "WQ Threshold" 
}

comp_plots_final <- comp_plots_final %>% layout(legend = list(x = 0, y = -0.12, orientation = "h"))
```

```{r, site_comp_tab, results = 'asis', eval = show_comp}
cat("## ", "All Sites", "\n")
cat("<h2>Monthly Water Quality Measurements", paste0("(", parkcode, " ", current, ")"),"</h2>")
```

```{r, site_comp_end, results = 'asis', include = show_comp}
fig_cap <- htmltools::withTags(body(
                          'The plots below compare monthly
                          measurements across all', long_name, 'sites during the',
                          current, 'field season. Only water quality parameters
                          that are measured at multiple sites are included. WQ thresholds
                          are derived from state surface water quality standards. See 
                          "About the Data" for more details.'))
cat(as.character(fig_cap))

```

```{r, site_comp_plots, results = 'show', out.height = "90%", eval = show_comp}
comp_plots_final
```

```{r site_tabs, warning = F, message = F, results='asis', eval = T}

for(i in seq_along(site_list)){
  site <- site_list[i] # remember to change this back to i
  site_name <- getSiteInfo(netnwd, parkcode = params$park, sitecode = site, 
                          info = "SiteName")
  num_plots <- length(plot_list[names(plot_list) == site])
  
  plot_title <- htmltools::withTags(h2('Historic', paste0('(',from, '–', to,')'),
                                                'vs. Current', paste0('(',current,')'), 'Measurements'))
                                                 
  fig_cap <- htmltools::withTags(body('Caption placeholder.'))
  
  fig_height <- ifelse(num_plots > 4, 6.5, 4.5)
  fig_width <- 9.3

  
  subplots <- subplot(plot_list[names(plot_list) == site][1:num_plots],
                      titleY = TRUE, titleX = FALSE, margin = 0.05,
                      nrows = ifelse(num_plots>4, 3, 2),
                      #heights = ifelse(num_plots>4, c(0.3, 0.35, 0.3), c(0.3, 0.3))) %>% 
                      heights = if(num_plots>4) {c(0.3,0.35,0.3)}, 
                      which_layout = 1) %>% 
             #style(showlegend = FALSE) %>% 
             layout(legend = list(x = 0, y = ifelse(num_plots>4, -0.05, -0.08),
                                  orientation = "h"))
  
  # Logical way to find and turn on poor water quality and wq thresholds
  # First turn them all off
  for (i in seq(1:length(subplots$x$data))) {
    subplots$x$data[[i]]$showlegend <- FALSE
  }
  
  # Find the first time the poor water quality point is used- returns the index number
  # find_pwq <- data.frame(pwq = lapply(seq_along(subplots$x$data), 
  #   function(i){
  #     #if(subplots$x$data[[i]]$name == "orange"){paste0(i)
  #     if(subplots$x$data[[i]]$marker$color[1] == "orange"){paste0(i)
  #       } else{NA}}) %>% 
  #     unlist()) %>% na.omit() %>% slice(1) %>% as.numeric()
  
  # Find the first time the water quality threshold is used- returns the index number
  find_wqt <- data.frame(wqt = lapply(seq_along(subplots$x$data),
    function(i){
      if(!is.null(subplots$x$data[[i]]$line$dash)){
      if(subplots$x$data[[i]]$line$dash == "dash"){
        paste0(i)
        } else{NA}}
        else{NA}
      } ) %>% unlist()) %>%
      na.omit() %>% slice(1) %>% as.numeric()
  
  # Find the first time an outlier is used
  # find_otl <- data.frame(pwq = lapply(seq_along(subplots$x$data),
  #   function(i){
  #     if(subplots$x$data[[i]]$marker$symbol == "asterisk"){paste0(i)
  #       } else{NA}}) %>%
  #     unlist()) %>% na.omit() %>% slice(1) %>% as.numeric()
  
  # Turn on the poor water quality and thresholds if they existed
  # if(!is.na(find_pwq)){
  #   subplots$x$data[[find_pwq]]$showlegend <- TRUE
  #   subplots$x$data[[find_pwq]]$name <- "Poor WQ value"}
  
  if(!is.na(find_wqt)){
    subplots$x$data[[find_wqt]]$showlegend <- TRUE
    subplots$x$data[[find_wqt]]$name <- "WQ threshold"}
  
  # if(!is.na(find_otl)){
  #   subplots$x$data[[find_otl]]$showlegend <- TRUE
  #   subplots$x$data[[find_otl]]$name <- "Outlier"}
  
  template <- paste0(
    "## {{site_name}}\n",
    "```{r {{site}}, fig.height=",fig_height, ", fig.width=", fig_width,", echo = FALSE}\n",
    "plot_title\n",
    "\n",
    "fig_cap\n",
    "subplots\n",
    "```\n",
    "\n"
  )
  
  # expand expressions within {{ }}
  tab <- knitr::knit_expand(text = template)
  
  # knit results
  cat(knitr::knit(text = unlist(tab), quiet = TRUE))
  
}

```