---
title: "About Tabs"
author: "Kate Miller"
date: "11/20/2020"
output: html_document
---
### About the Data
<details open><summary><b>Parameters</b></summary>
This section is currently copied from the water visualizer and should be edited to reflect the goals of this project. More information should be given interpreting parameters that are paired (e.g. DO and temperature, SpC and discharge). Note: total phosphorus (TP) and total nitrate (TN) will be plotted in a later iteration of this draft. 

<details><summary>Acid Neutralizing Capacity (ANC)</summary> ANC is the prime indicator of a waterbody's susceptibility to acid inputs. The higher the ANC of a waterbody, the better able it is to resist the effects of acid. It is a measure of the amount of compounds in the water that neutralize low pH. The measured ANC refers to the alkalinity of an unfiltered water sample (i.e. alkalinity due to both dissolved and suspended matter). This is different than the pH of the stream, as pH measures acidity, but does not measure "buffering capacity". ANC is typically caused by anions (negatively charged particles) in natural waters that can enter into a chemical reaction with a strong acid. These are primarily the carbonate (CO32-) and bicarbonate (HCO3-) ions. Borates, phosphates, silicates, arsenate, ammonium, and organic ligands (e.g. acetate and propitiant) can also contribute to alkalinity when present.

</details>

<details><summary>Dissolved Oxygen (DO)</summary> DO is a measure of the amount of oxygen in water. DO is necessary in aquatic systems for the survival and growth of many aquatic organisms. Dissolved oxygen can enter water by photosynthesis of plants or directly from the atmosphere, and it is lost by temperature rise, plant and animal respiration, and bio-chemical reactions. The DO concentration of surface water also depends on water temperature and air pressure. High pressures and cool temperatures allow more oxygen to be dissolved in the water. Due to changes in temperature, DO has strong daily and seasonal variability.

Low DO is of greatest concern because of its detrimental effects on aquatic life. Conditions that generally contribute to low DO levels include warm temperatures, low flows, water stagnation and shallow gradients in streams, organic matter inputs, and high respiration rates. Decay of excessive organic debris from aquatic plants, municipal or industrial discharges, or storm runoff can also cause low DO. Insufficient DO can lead to unsuitable conditions for aquatic life.

We include two measures of DO: milligrams per liter (mg/L) and % saturation. Milligrams per liter indicates the absolute amount of oxygen present in the water, whereas % saturation indicates how much is present as compared to a theoretical maximum determined by water temperature.

</details>

<details><summary>pH</summary> The pH of water is a measure of how acidic or basic a stream is. The term pH stands for "power of hydrogen." More hydrogen ions results in a lower pH. pH is measured on a scale that most commonly ranges from 0 (acid) to 14 (basic/alkaline). Pure water has a pH of 7 (neutral). The pH scale is "logarithmic" meaning each pH unit increase represents a 10X decrease in hydrogen ion concentration.

The pH of water is important to aquatic life, as it has a profound impact on the toxicity and solubility of many chemicals. The toxicity of ammonia, aluminum, and some other contaminants is partially determined by pH. Changes in pH affect the dissociation of weak acids or bases, which in turn affects the toxicity of many compounds. For example, hydrogen cyanide toxicity to fish increases with lowered pH, whereas rapid increases in pH increase NH3 (ammonia) concentrations. Metal mobility is also enhanced by low pH which can have a significant impact on water bodies located in areas contaminated by heavy metals (e.g. mining).

</details>

<details><summary>Specific Conductance</summary> Specific conductance is a temperature corrected measure of the electrical conductivity of water and is directly related to concentration of ions. Conductivity is a measure of the capacity of water to conduct an electrical current. The conductivity of water is highly dependent on temperature and may change as much as 3% for each 1 degree C change. Thus a large apparent change in conductivity may simply be due to water temperature, and not due to changes in ions in the water. Specific conductance is a measure of conductivity of water which takes water temperature into account. Specific conductance is dependent upon the types and quantities of dissolved substances and is a good indication of total dissolved solids and total ion concentration.

The electrical conductivity of a water body has little or no direct effect on aquatic life. However, an increase in conductivity may indicate an increase of an ion that is toxic to aquatic life. Specific conductance is also useful in estimating the concentration of dissolved solids in water. Electric current is carried by dissolved inorganic solids such as chloride, carbonate, nitrate, sulfate, and phosphate anions (negatively charged particles), as well as sodium, calcium, magnesium, potassium, iron, and aluminum cations (positively charged particles). Common sources of pollution that can affect specific conductance are deicing salts, dust reducing compounds, agriculture (primarily from the liming of fields), and acid mine drainage (U.S. Geological Survey 1980, Stednick and Gilbert 1998, National Park Service 2002). In an analysis of data from the Maryland Biological Stream Survey, Morgan et al. (2007) found a critical value for conductivity of less than 247 uS/cm for macroinvertebrates and less than 171 uS/cm for fish.

</details>

<details><summary>Total Nitrate</summary> Nitrate is one of the dissolved, inorganic forms of nitrogen most available for biological uptake and the chemical transformation that can lead to eutrophication of water bodies. Nitrate is highly mobile in surface and groundwater and may seep into streams, lakes, and estuaries from groundwater enriched by animal or human wastes and commercial fertilizers. High concentrations of nitrate can enhance the growth of algae and aquatic plants in a manner similar to enrichment in phosphorous and thus cause eutrophication of a water body. In most natural waters, inorganic nitrogen as ammonium or nitrate is not the growth-limiting nutrient unless phosphorous is unusually high.

Nitrate 2007-2013: Between 2007 and 2013, total nitrate was measured using the chromotropic acid method.<br>
Nitrate 2013-2016: Between 2013 and 2016, total nitrate was measured using the dimethylphenol method.

</details>

<details><summary>Total Phosphorus</summary> Phosphorus (measured as PO4) is frequently a limiting nutrient in aquatic systems. A minor increase in phosphorous concentration can significantly affect water quality by changing the population and community dynamics of algae and diatoms leading to eutrophication (Allan 1995). Phosphorus is singled out as an especially important actor in the Heinz Center Report (2002) on the state of nation's ecosystems. Sources of phosphorous include sediments, fertilizer application (e.g. irrigation return flow), soaps, and detergents.

Total Phosphorus 2009-2013: Between 2009 and 2013, total phosphorus was measured using the acid persulfate digestion method.<br>
Total Phosphorus 2013-2016: Between 2013 and 2016, total phosphorus was measured suing the ascorbic acid method.

</details>

<details><summary>Water Temperature</summary> Several of the water chemistry parameters are water temperature dependent, such as: DO and specific conductance. High temperature can also stress aquatic life particularly those adapted to habitats with cooler temperatures such as trout.

</details>
</details><br>

<details open><summary><b>Site Descriptions</b></summary>
Site descriptions here. 

</details>